### ISSUE TITLE
Episodes are not updated any more

### ISSUE THREAD

**Issue by OBedford** [sorax/plugin.video.sandmann#8] opened 2022-03-01 22:51 UTC
Hi,
I'm not sure if this is a real issue or perhaps a local problem on my side: since 23.02.22 we don't get updates to the episode list.
I've found the following in the logs (recurring):
"2022-03-01 22:45:12.933 T:787370880   ERROR: /storage/.kodi/addons/plugin.video.sandmann/addon.py:77: SyntaxWarning: name 'refresh_timer' is assigned to before global declaration
                                              global refresh_timer"
Running KODI 18.9/LibreELEC 9.2.8 on a Raspberry Pi 3.
Regards,
Oliver

**Comment by kevleodev** [comment] 2022-03-02 15:50
I've got the same issue - no new episodes since 23.02.2022.

**Comment by sorax** [comment] 2022-03-03 20:37
can confirm that - will investigate

**Comment by sorax** [comment] 2022-03-03 20:50
looks like I found something in the ardmediathek...
https://api.ardmediathek.de/page-gateway/widgets/ard/asset/Y3JpZDovL3JiYi1vbmxpbmUuZGUvc2FuZG1hbm4 
seems to be the new api now

**Comment by sorax** [comment] 2022-03-04 07:25
Status:
- [x] getting the list of episodes 
- [ ] parsing the episode data (title, description, images)
- [ ] getting the video-url

**Comment by sorax** [comment] 2022-03-06 21:38
[PR](https://github.com/xbmc/repo-plugins/pull/3914) for matrix is submitted
it this is merged by the repo-owners I can submit v2 to the Leia repo as well

**Comment by sorax** [comment] 2022-03-08 18:54
the PR is merged and the add-on on matrix should auto-update and work now.
can anybody confirm that? (I have only leia in use here)

status: still working to get the addon updated for leia as well

**Comment by kevleodev** [comment] 2022-03-08 19:23
I can confirm that the plugin auto-updates and works again on matrix. Thanks a lot, bed time routine is saved 😄

**Comment by sorax** [comment] 2022-03-11 07:34
The [PR](https://github.com/xbmc/repo-plugins/pull/3915) with the Update/Fix for Kodi Leia has been merged as well.
So v2.0 is now available for Kodi Leia, Matrix and Helix.  From my point of view the Issue is solved and can be closed.

**Comment by OBedford** [comment] 2022-03-12 16:14
Update for Kodi Leia (LibreELEC 9.2.8 on Raspberry Pi 3 B) appeared today, but failed to update/install due to unresolvend dependency with xbmc.python version 3.0.0. I assume Python 3 is generally no available for Leia?

Currently I'm a bit reluctant to update to Matrix (fresh code for RPi 3, hardware support working?).

Kind regards,
Oliver

**Comment by sorax** [comment] 2022-03-13 10:29
Hi @OBedford,
thanks for letting me know - I will try my best to fix this for Leia asap!

I have Kodi running on a Raspberry Pi 3B as well. 
Last week I upgraded to [Matrix](https://releases.libreelec.tv/LibreELEC-RPi2.arm-10.0.2.img.gz) -> installed from scratch.
This worked fine and I had no issues.

**Comment by OBedford** [comment] 2022-03-19 22:23
Hi,
I've just upgrade to LibreELEC 10.0.2/Kodi 19.4. Everything seems to be working fine - incl. the Sandmann Addon (two more kids happy ;-) But this means I can't comment on problems on Leia anymore.

Thanks a lot for your work!
Kind regards,
Oliver

**Comment by sorax** [comment] 2022-04-03 12:11
I now have Leia & Matrix running on my laptop, so I can test both versions.
Version [v2.1.0 for Leia](https://github.com/xbmc/repo-plugins/pull/3929) and Version [v2.1.1 for Matrix](https://github.com/xbmc/repo-plugins/pull/3928) are now merged into the Kodi Repo and do fix the issues.

So from my point of view the Issue can be closed.

**Closed by sorax** 2022-04-03 12:11 UTC
Labels: bug, v2
